INPUT_FILE = sampledata
OUT_FILE = out
EXEC_NAME = mp.m

help:
	@echo "IMPORTANT: This program requires Octave to work\n"
	@echo "Usage: Makefile target\n"
	@echo "Targets available: mccullogh"
	@echo "\t mccullogh: Executes mp.m to solve the displacing bit problem taking"
	@echo "\t\t inputs from $(INPUT_FILE) and writing output to $(OUT_FILE)\n"

mccullogh:
	./$(EXEC_NAME) $(INPUT_FILE) $(OUT_FILE)